### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mikekestemont** [hipster-philology/pandora#2]
- Add installation guidelines.
- pip install

**Comment by PonteIneptique** [comment]
I can do this one :)

**Comment by PonteIneptique** [comment]
A little improved by #4

**Comment by mikekestemont** [comment]
Note that we can only support tensorflow anymore for keras models, and that in the keras config file we need settings:

```json
{
    "floatx": "float32",
    "image_data_format": "channels_first",
    "epsilon": 1e-07,
    "backend": "tensorflow"
}
```
Should we enforce this in the code?

**Comment by PonteIneptique** [comment]
I think we can close this. :)
