### ISSUE TITLE
Opt-in epoch step results evaluation with CLI

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#20]
Make the printing of tests during training optional.
Might be related to #8

**Comment by Jean-Baptiste-Camps** [comment]
Would it not be good too to be able to test only every nth epoch ? Training takes some time, and maybe we don't need to do it each time.

**Comment by PonteIneptique** [comment]
I have not looked at the repercussion of this. Maybe it can be another issue, once this one is solved ? ;)

**Comment by PonteIneptique** [comment]
@mikekestemont I am not sure, looking at the code, that dev_prev and train_pred are used by the NN. Could you confirm this ?

**Comment by Jean-Baptiste-Camps** [comment]
Ok, the current code causes an issue, or, at least, CLI and documentation need to be modified. 
If I do

    python3 main.py config_test.txt --dev data/test/dev --train data/test/train --test data/test/test

I get the error
    
    raise ValueError('Please do not call .test() if no test data is available.')
    ValueError: Please do not call .test() if no test data is available.

Though 'test' is not empty. It is, I think, because of:

    def main(config, train, dev, test=None, load=False, verbose=True, **kwargs):

**Comment by PonteIneptique** [comment]
I do not see how this would have changed this. Can you show the config_test.txt content ?

**Comment by PonteIneptique** [comment]
I'd say it's based on the loading of a precedent config file where include_test could be none. Bue I'd need to see your config_test.txt

**Comment by Jean-Baptiste-Camps** [comment]
Sorry, meanwhile I saw this was because of my config.txt.

**Comment by mikekestemont** [comment]
Are you sure `dev_prev` and `train_pred`are the exact variable names used? In which file?

**Comment by PonteIneptique** [comment]
See my answer in the correct issue https://github.com/hipster-philology/pandora/issues/26#issuecomment-331795120
