### ISSUE TITLE
Testing every nth epochs to save time

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#26]
@Jean-Baptiste-Camps in #20 

> Would it not be good too to be able to test only every nth epoch ? Training takes some time, and maybe we don't need to do it each time.

We are awaing on @mikekestemont feeling if this is gonna break anything. My own feeling is that it would not.

**Comment by PonteIneptique** [comment]
@MikeKestemont I'll answer to you question here :
The question is about tagger.py :

```python
# Get train preds:
        train_preds = self.model.predict(train_in, batch_size=self.batch_size)
        if isinstance(train_preds, np.ndarray):
            train_preds = [train_preds]

        # Get dev preds
        dev_preds = None

```

**Comment by mikekestemont** [comment]
Well, they are obviously used here for scoring: score_dict =
self.get_score_dict(train_preds, dev_preds, verbose=verbose)
Right?

**Comment by PonteIneptique** [comment]
This I got but I am not sure how necessary is score dict. And it could be that outside prototyping it would be good to avoid prediction if possible. My feeling, looking at the code, is that score dict is only useful for humans.

**Comment by mikekestemont** [comment]
Score dict is what prints your current accuracies so I would say it is crucial to monitor training progress, especially to add early stopping one day.

**Comment by PonteIneptique** [comment]
I agree but this means it can be a little more modular : test first
ten,then monitor each ten.(again, this would be an option, not the default )

Le 25 sept. 2017 9:32 AM, "Mike Kestemont" <notifications@github.com> a
écrit :
