### ISSUE TITLE
Printing or exporting score dict should be done outside of evaluation and test

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#28]
Just using this outside would allow for lighter API and centralized "logging". I can see the use of an export to csv for example.

**Comment by mikekestemont** [comment]
I agree that through logging we could better control  where this stuff gets shown, but by default I would keep it visible during training.

**Comment by PonteIneptique** [comment]
Completely agree.

Le 25 sept. 2017 9:34 AM, "Mike Kestemont" <notifications@github.com> a
écrit :

**Comment by PonteIneptique** [comment]
I think get_score_dict should get fed to a output class that could : print, log, export csv of stats. This would also allow for less modifications on the long term in tagger.py

**Comment by mikekestemont** [comment]
fine with me

On Mon, Sep 25, 2017 at 10:25 AM, Thibault Clérice <notifications@github.com
