### ISSUE TITLE
Merging the pytorch branch

### ISSUE THREAD

**Issue by emanjavacas** [hipster-philology/pandora#38]
Hello everybody,

We are planning to retake work on the pytorch branch of the repository. In the meantime there has also been some work on the master branch (kudos!). I checked for compatibility and the branches wont merge automatically, but I have the feeling it shouldn't be too much work to make it work. 

If you agree, I could open a PR and somebody else could review it (otherwise I could do it myself, but it wont be as clean and transparent).

We know that this is a big move but we are confident that the model will improve in performance given that we will be able to implement things like attention, etc...

What do you think?

**Comment by emanjavacas** [comment]
~Could we add a milestone for this? (I am currently just a member and I don't seem to be able to do it).~
Member can also create milestones...

**Comment by Jean-Baptiste-Camps** [comment]
Hi,
This is great news ! I'm all for merging the two branches. It will also help if we want to be able not to lag too much behind in the Keras evolution as well.  I think that, before merging, we should also make another release (0.0.1b), in case we need a stable version of Pandora.
Meanwhile, I have created the milestone.

**Comment by PonteIneptique** [comment]
Please go ahead ! :)

**Comment by PonteIneptique** [comment]
Can we keep the ability to switch to either a tensorflow or a keras model ?

**Comment by emanjavacas** [comment]
Sure, I have set up an interface and we are trying to make sure that you can load either model.
That said, the goal is to use pytorch to be more flexible and get performance improvements, so in the long run there might not be too compelling reasons to use the keras implementaiton.

**Comment by PonteIneptique** [comment]
Good for me :)

**Comment by emanjavacas** [comment]
Cool. I think we are good to merge. Pytorch model is learning. I will create the PR and let's see how painful it is to merge.
