### ISSUE TITLE
Padding, end and beginning of sequence symbols

### ISSUE THREAD

**Issue by emanjavacas** [hipster-philology/pandora#41]
The current approach of using '%', '$' and '|' is very brittle if the input text includes one of those characters.
I think this could be abstracted using less ambiguous symbols and putting as constants somewhere in a utils.py file instead of hardcode them.

**Comment by emanjavacas** [comment]
I am not sure but to me it looks like `'$'` is sometimes used as padding and sometimes as end-of-sequences symbol.

See here: https://github.com/hipster-philology/pandora/blob/master/pandora/preprocessing.py#L567
but here: https://github.com/hipster-philology/pandora/blob/master/pandora/preprocessing.py#L144

**Comment by mikekestemont** [comment]
Yes, I agree that the whole system is too brittle right now: can you make a
suggestion as to which symbols we could use?

**Comment by emanjavacas** [comment]
I think the actual values don't matter as long as they are rare enough to
not appear in the original vocab. The point is more about making them
package level constants somewhere in a utils file

**Comment by emanjavacas** [comment]
solved by 1f169ea7ab7ca576fb580f150032a0ee3604b60e

**Comment by mikekestemont** [comment]
very clean, thanks!

On Mon, Oct 2, 2017 at 5:30 PM, Enrique Manjavacas <notifications@github.com
