### ISSUE TITLE
Pypi

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#5]
- [ ] Register the package as `philology-pandora` (?) on http://pypi.python.org/ ( See http://peterdowns.com/posts/first-time-with-pypi.html )
- [ ] Add me and @Jean-Baptiste-Camps as maintainers ? ( http://stackoverflow.com/questions/12857123/pypi-role-maintenance-owners-vs-maintainers )

Once this is done, it will be up to me to setup the repository for a `setup.py` ( See #6 )

**Comment by mikekestemont** [comment]
That would be cool. I'm only worried that Tensorflow/Pytorch are not that easy to pip-install yet. Would that be an issue?

**Comment by Jean-Baptiste-Camps** [comment]
I don't know for Pytorch, but, in my experience, installing Tensorflow from requirements.txt with pip works fine these days (that is, if you don't want to compile it from source yourself).

**Comment by emanjavacas** [comment]
For pytorch it wont work as smoothly. Actually, in my experience it doesn't work so smoothly for TF as soon as you want something fancier (particular cuda version). I'd be in favor of sending future users to either website and come back for further installation instructions.

**Comment by PonteIneptique** [comment]
Looking at the PyTorch install, I agree it won't be as smooth. I am therefore closing this issue.

What we need though is to make releases more often.
