### ISSUE TITLE
config dir

### ISSUE THREAD

**Issue by mikekestemont** [hipster-philology/pandora#60]
it's useful to have example config files but they clutter the topdir a little. @Jean-Baptiste-Camps should we move into a toplevel dir of their own?

**Comment by Jean-Baptiste-Camps** [comment]
We could cerrtainly have a `config_examples` dir, or something equivalent. Another question is: should we exclude (most of) them from the git repository ? For now, I have stopped to commit my various configurations (Chrestien, Montferrand, etc.), not to drown the repository in them. What do you think ?

**Comment by PonteIneptique** [comment]
I think we should gitignore *.txt file at root and have a config_example directory.
Alternatively, we also need to spawn git repository that demonstrate examples with config, built model as attached binary to release, and finally source data

**Comment by PonteIneptique** [comment]
Fixed by #66
