### ISSUE TITLE
Information to everyone : code of conduct regarding direct push

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#61]
Dear all,
I think it would be better to enforce, for everyone, the need to go through PR. I am willing to enact this by setting up the repo for this (github allows to block push to specific branch). I think it would allow a more streamlined development and also allows people to be aware of changes. The four or five of us are active enough to get back in an acceptable timeframe to merge the PR.

Are you okay with this ?

**Comment by mikekestemont** [comment]
sure.

**Comment by Jean-Baptiste-Camps** [comment]
Certainly.

**Comment by PonteIneptique** [comment]
Good :) I propose to put reviews as necessary before merge as well.
