### ISSUE TITLE
Additional corpora

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#64]
I opened a Wiki page about best methods for sharing corpora : https://github.com/hipster-philology/pandora/wiki/Sample-or-example-data-for-Pandora-:-contributing-a-repository

This is for your information.
To open a repository, juste create one or ask for the rights with the name of the repository you want to create

**Comment by PonteIneptique** [comment]
I am gonna clean up issue #55 about this thing

**Comment by PonteIneptique** [comment]
>  Regardless the current error I am having now, we really need a minimal working example with a packaged corpus.
@emanjavacas 

> I can push a test corpus very quickly into the repository, if needed, I have a few ones at hand (and working properly now).
@Jean-Baptiste-Camps 

> I'd prefer to have full example repositories and few small sample packaged here
@ponteineptique

> Ok, I can do that. I already have a repository for some of my data, that will be progressively enriched. I can add a pandora-data folder, or something like that there (https://github.com/Jean-Baptiste-Camps/Geste), and a sample (data + config) here.
@Jean-Baptiste-Camps

**Comment by Jean-Baptiste-Camps** [comment]
Trying to train on the sample corpus I added, I saw an old bug resurfacing when including morph, equivalent to #12 but on morph this time. I'll comment it here.

**Comment by PonteIneptique** [comment]
Fixed by #66
