### ISSUE TITLE
Main.py and tagger.train()

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [hipster-philology/pandora#8]
I am not sure this one is worth an issue, but since there might be something I am missing here:
why do we use
```
    for i in range(int(params['nb_epochs'])):
        tagger.epoch()
        tagger.save()
```
in Main.py, instead of the existing 
`    tagger.train()`
?

**Comment by mikekestemont** [comment]
This makes sure that your tagger gets saved after every epoch... Fine with me to change this!
