### ISSUE TITLE
Add a linter for future work

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#90]
This would allow us to work with the same syntax.

I would advocate for rst's style docstrings in terms of settings. I find them much more readable and precise than Google's one :) Any other setting wished ?

**Comment by PonteIneptique** [comment]
I just started configure Codacy.com

**Comment by PonteIneptique** [comment]
Done

**Comment by mikekestemont** [comment]
For the existing docstrings I have adopted sklearn's conventions so far.
