### ISSUE TITLE
Latest PR broke tests

### ISSUE THREAD

**Issue by PonteIneptique** [hipster-philology/pandora#97]
It's my fault for not waiting the PR results...

@emanjavacas can you look at it since this is some code you added ? https://travis-ci.org/hipster-philology/pandora/builds/298499051

**Comment by PonteIneptique** [comment]
@emanjavacas It seems you coded with new formatted string from 3.6. I would prefer the codebase to remain 3.5 compliant at least for some time. Could you revert f-strings to .format() ones ?

**Comment by mikekestemont** [comment]
I am actually in favor of f-strings along the way: what would be the
objective reason to stick to 3.5?

**Comment by PonteIneptique** [comment]
The default on Ubuntu 16.04 is still 3.5 which means not well versed into python people that just want to try this out are gonna suffer from this. And in general, it's good to stay retro-compatible with the before-the-last version...

On another note, I don't like f-strings, but that's my opinion. To me they are something I would have preferred to see only in PhP because even if they are convenient, they are more than easy creators of problems... At least format, that takes few characters more, makes variable concatenation and variable purpose clear.

**Comment by mikekestemont** [comment]
But isn't Ubuntu at 17.10 already?

**Comment by PonteIneptique** [comment]
17.10 is not a LTS. 18.04 is Q1/Q2 2018 : https://www.ubuntu.com/info/release-end-of-life

And even when 18.04 is turning around, I doubt many people will turn to 18.04 that quickly. If this is only about cosmetic improvement, such as f-strings, I think we can just not use them :)

**Comment by PonteIneptique** [comment]
Fix proposed in #101

**Comment by PonteIneptique** [comment]
Fixed by #101
